# ไฟล์: frontend/docker-compose.yml
version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_STRIPE_PUBLISHABLE_KEY: pk_test_YOUR_KEY_HERE
    environment:
      - VITE_STRIPE_PUBLISHABLE_KEY=pk_test_YOUR_KEY_HERE
    container_name: shop_frontend
    command: npm run dev -- --host 0.0.0.0 --port 5173
    # environment:
    #   - VITE_API_TARGET=http://shop-backend:8000
    ports:
      - "3000:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - shop-net

networks:
  shop-net:
    external: true
    name: shop-network

  
